#ifndef __UIAboutDialog__
#define __UIAboutDialog__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

//// end generated include

/** Implementing AboutDialog */
class UIAboutDialog : public AboutDialog
{
protected:
    // Handlers for AboutDialog events.
    void AboutDialogOnInitDialog(wxInitDialogEvent& event);
    void m_hyperlinkApplicationWebsiteOnHyperlink(wxHyperlinkEvent& event);
    void m_hyperlinkApplicationEmailOnHyperlink(wxHyperlinkEvent& event);
    void m_buttonOKOnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    UIAboutDialog(wxWindow* parent);
    //// end generated class members
};

#endif // __UIAboutDialog__
