#ifndef __UIFormatsDialog__
#define __UIFormatsDialog__

/**
@file
Subclass of FormatsDialog, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dirdlg.h>
#include "UIPresetsDialog.h"

class CFormat
{
};

/** Implementing FormatsDialog */
class UIFormatsDialog : public FormatsDialog
{
protected:
    // Handlers for FormatsDialog events.
    void FormatsDialogOnInitDialog(wxInitDialogEvent& event);
    void m_menuItemItemsDuplicateOnMenuSelection(wxCommandEvent& event);
    void m_menuItemItemsDeleteAllOnMenuSelection(wxCommandEvent& event);
    void m_menuItemItemsDeleteOnMenuSelection(wxCommandEvent& event);
    void m_menuItemItemsAddOnMenuSelection(wxCommandEvent& event);
    void m_buttonDuplicateOnButtonClick(wxCommandEvent& event);
    void m_buttonDeleteAllOnButtonClick(wxCommandEvent& event);
    void m_buttonDeleteOnButtonClick(wxCommandEvent& event);
    void m_buttonAddOnButtonClick(wxCommandEvent& event);
    void m_textCtrlPropertyNameOnText(wxCommandEvent& event);
    void m_textCtrlPropertyIdOnText(wxCommandEvent& event);
    void m_spinCtrlPropertyPriorityOnSpinCtrl(wxSpinEvent& event);
    void m_spinCtrlPropertyPriorityOnSpinCtrlText(wxCommandEvent& event);
    void m_textCtrlPropertyInputExtensionsOnText(wxCommandEvent& event);
    void m_textCtrlPropertyOutputExtensionOnText(wxCommandEvent& event);
    void m_radioBtnTypeEncoderOnRadioButton(wxCommandEvent& event);
    void m_radioBtnTypeDecoderOnRadioButton(wxCommandEvent& event);
    void m_textCtrlPropertyExitCodeSuccessOnText(wxCommandEvent& event);
    void m_comboBoxDefaultPresetOnCombobox(wxCommandEvent& event);
    void m_comboBoxDefaultPresetOnText(wxCommandEvent& event);
    void m_buttonPropertyDefaultPresetEditOnButtonClick(wxCommandEvent& event);
    void m_checkBoxPropertyPipeInputOnCheckBox(wxCommandEvent& event);
    void m_checkBoxPropertyPipeOutputOnCheckBox(wxCommandEvent& event);
    void m_textCtrlPropertyFunctionOnText(wxCommandEvent& event);
    void m_buttonPropertyFunctionBrowseOnButtonClick(wxCommandEvent& event);
    void m_textCtrlPropertyTemplateOnText(wxCommandEvent& event);
    void m_textCtrlPropertyPathOnText(wxCommandEvent& event);
    void m_buttonPropertyPathBrowseOnButtonClick(wxCommandEvent& event);
    void m_buttonImportOnButtonClick(wxCommandEvent& event);
    void m_buttonExportOnButtonClick(wxCommandEvent& event);
    void m_buttonOKOnButtonClick(wxCommandEvent& event);
    void m_buttonCancelOnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    UIFormatsDialog(wxWindow* parent);
    //// end generated class members
protected:
    std::vector<CFormat> m_Items;
    std::vector<ItemColumn> m_Columns;
};

#endif // __UIFormatsDialog__
